"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const token = require("./token");
exports.token = token;
const auth = require("./auth");
exports.auth = auth;
const redisConnect = require("./redisConnect");
exports.redisConnect = redisConnect;
const bots = require("./bots");
exports.bots = bots;
const spam = require("./spam");
exports.spam = spam;
const backbone = require("./backbone");
exports.backbone = backbone;